### PR TITLE
make expiringdict pickable and extend some functions

### PR DESCRIPTION
**Pull request by bitranox**
- make expiringdict pickable
- can now copy from dict, OrderedDict, expiringdict (see pytest files)

### CODE REVIEW

**Comment by bitranox** [comment]
uh that was easy to pass - especially when no nosetests are done via tox - You need look into it, if You want i can adjust - to get rid of tox and make a proper travis.yml
Looks a bit abandonded ...

**Comment by bitranox** [comment]
thanks for merging !
maybe update the tests ? CI build does not run the tests, so it is always passing ...

**Comment by horkhe** [comment]
We need to ditch tox and just rely on travis

**Comment by bitranox** [comment]
if You want I can do that in the next days - just tell me which Python Versions You want to cover,
WINE ? Windows ? OSx ? I have a very nice template to test it all ...

**Comment by horkhe** [comment]
@bitranox I have fixed the tests to run under Travis CI to run with 2.7 and 3.6. Feel free to submit a PR if you need something else.

**Pull request merged**
